MusicStoreClient/MusicStoreClient/Models/item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MusicStoreClient.Models
{
    public class item
    {
        public int ItemId { get; set; }
        public Nullable<int> Category { get; set; }
        public string ItemName { get; set; }
        public string EventAct { get; set; }
        public string even { get; set; }
        public Nullable<decimal> Price { get; set; }

        public virtual category category1 { get; set; }
    }
}

MusicStoreClient/MusicStoreClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicStoreClient.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MusicStoreClient/MusicStoreClient/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Threading.Tasks;
using MusicStoreClient.Models;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace MusicStoreClient.Controllers
{
    public class ItemController : Controller
    {
        //
        // GET: /Item/
        CategoryController mc = new CategoryController();

        public async Task<ActionResult> Index(int id = 0)
        {
            List<item> listitem = new List<item>();
            if (id == 0)
                listitem = await getall();
            else
            {
                item item = await getdetails(id);
                listitem.Add(item);
            }
            var category = await mc.getall();
            var listjoin = (from i in listitem.ToList()
                            join c in category.ToList()
                            on i.Category equals c.CategoryId
                            select new
                            {
                                i.ItemId,
                                i.ItemName,
                                i.Price,
                                c.CategoryName,
                                i.even,
                                i.EventAct
                            }).ToList();
            List<itemjoincategory> listijc = new List<itemjoincategory>();
            foreach(var data in listjoin)
            {
                itemjoincategory ijc = new itemjoincategory();
                ijc.ItemId = data.ItemId;
                ijc.ItemName = data.ItemName;
                ijc.Price = data.Price.Value;
                ijc.CategoryName = data.CategoryName;
                ijc.even = data.even;
                ijc.EventAct = data.EventAct;
                listijc.Add(ijc);
            }
            
            return View(listijc.ToList());
        }

        public async Task<ActionResult> testforhome()
        {
            List<item> listitem = await getsampleforhome();
            ViewBag.listtools = await gettoolsforhome();
            return View(listitem);
        }

        public ActionResult viewforhome(List<item> lis)
        {
            return PartialView("_homeview", lis);
        }

        public async Task<ActionResult> tes()
        {
            List<item> listitem = await getsampleforhome();
            return RedirectToActionPermanent("viewforhome", listitem);
        }

        public async Task<List<item>> getsampleforhome()
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:44093/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = await client.GetAsync("api/itemapi");
                var jsonstring = await response.Content.ReadAsStringAsync();
                var listitem = JsonConvert.DeserializeObject<IEnumerable<item>>(jsonstring);
                if (response.IsSuccessStatusCode)
                {

                    return listitem.Where(a=>a.Category == 1).OrderByDescending(a => a.ItemId).Take(4).ToList();
                }
                return null;
            }
        }

        public async Task<List<item>> gettoolsforhome()
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:44093/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = await client.GetAsync("api/itemapi");
                var jsonstring = await response.Content.ReadAsStringAsync();
                var listitem = JsonConvert.DeserializeObject<IEnumerable<item>>(jsonstring);
                if (response.IsSuccessStatusCode)
                {

                    return listitem.Where(a => a.Category == 2).OrderByDescending(a => a.ItemId).Take(4).ToList();
                }
                return null;
            }
        }

        public async Task<List<item>> getall()
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:44093/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = await client.GetAsync("api/itemapi");
                var jsonstring = await response.Content.ReadAsStringAsync();
                var listitem = JsonConvert.DeserializeObject<List<item>>(jsonstring);
                if (response.IsSuccessStatusCode)
                {
                    return listitem;
                }
                return null;
            }
        }

        public async Task<ActionResult> makehomepage()
        {
            return View();
        }

        public async Task<item> getdetails(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:44093/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                HttpResponseMessage response = await client.GetAsync("api/itemapi/" + id);
                if (response.IsSuccessStatusCode)
                {
                    item item = await response.Content.ReadAsAsync<item>();
                    return item;
                }
                return null;
            }
        }

    }
}

MusicStoreClient/MusicStoreClient/Views/Item/Index.cshtml
@model IEnumerable<MusicStoreClient.Models.itemjoincategory>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ItemId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.even)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventAct)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.even)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventAct)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ItemId }) |
            @Html.ActionLink("Details", "Details", new { id = item.ItemId}) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ItemId })
        </td>
    </tr>
}

</table>

MusicStoreClient/MusicStoreClient/Views/Item/_homeview.cshtml
@model IEnumerable<MusicStoreClient.Models.item>
@{var count = 0;
  }
<table>
    <tr>
@foreach (var item in Model) {
    count = count + 1;
    var txt = string.Concat("/Images/orderedList", count, ".png");
    
    <td>
        <table>
    <tr>
        <td>
            <img src=@txt />
        </td>
        <td>
        <table>
            <tr>
                <th> @Html.DisplayFor(modelItem => item.ItemName) </th>
            </tr>
            <tr>
                <td> @Html.DisplayFor(modelItem => item.Price) </td>
            </tr>
            <tr>
                <td> @Html.DisplayFor(modelItem => item.EventAct) </td>
            </tr>
            <tr>
                <td>
                    @Html.ActionLink("Detail","Index",new{id = item.ItemId})
                </td>
            </tr>
        </table>
        </td>
    </tr>
         </table>
    </td>
    if (count == 2)
    {<tr></tr>;
    }
}
</tr>
</table>
@section scripts{
    <script type="text/javascript">
        function getdataitem(id) {
            window.location("Item/Index/"+id);
        }
    </script>
}

MusicStoreClient/MusicStoreClient/Views/Item/makehomepage.cshtml
@* System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper *@
@using System.Web.Mvc;
@{
    ViewBag.Title = "makehomepage";
}

<h2>makehomepage</h2>
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Wellcome to</h1>
                <h2>MVC Music Store</h2>
            </hgroup>
        </div>
    </section>
}
<h3>We suggest to View:</h3>
<div>
@{Html.RenderAction("tes", "Item", new { });}
    </div>

MusicStoreClient/MusicStoreClient/Views/Item/testforhome.cshtml
@model IEnumerable<MusicStoreClient.Models.item>
@using MusicStoreClient.Models;
@{var count = 0;
  }
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Wellcome to</h1>
                <h2>MVC Music Store</h2>
            </hgroup>
        </div>
    </section>
}
<h2>We suggest to View:</h2>
<h3> Music Tools </h3>
<section class="featured">
        <div class="content-wrapper">
<table>
    <tr>
@foreach (var item in Model) {
    count = count + 1;
    var txt = string.Concat("/Images/orderedList", count, ".png");
    
    <td>
        <table border="1">
    <tr>
        <td>
            <img src=@txt />
        </td>
        <td>
        <table>
            <tr>
                <th> @Html.DisplayFor(modelItem => item.ItemName) </th>
            </tr>
            <tr>
                <td> @Html.DisplayFor(modelItem => item.Price) </td>
            </tr>
            <tr>
                <td> @Html.DisplayFor(modelItem => item.EventAct) </td>
            </tr>
            <tr>
                <td>
                    @Html.ActionLink("Detail","Index",new{id = item.ItemId})    |
                    Buy
                </td>
            </tr>
        </table>
        </td>
    </tr>
         </table>
    </td>
    if (count == 2)
    {<tr></tr>;
    }
}
</tr>
</table>
            </div>
    </section>
<label><u>View More</u></label>

<h3> CD/DVD </h3>
<section class="featured">
        <div class="content-wrapper">
<table>
    <tr>
@{count = 0;}
@foreach (item item in ViewBag.listtools)
{
    count = count + 1;
    var txt = string.Concat("/Images/orderedList", count, ".png");
    
    <td>
        <table border="1">
    <tr>
        <td>
            <img src=@txt />
        </td>
        <td>
        <table>
            <tr>
                <th> @Html.DisplayFor(modelItem => item.ItemName) </th>
            </tr>
            <tr>
                <td> @Html.DisplayFor(modelItem => item.Price) </td>
            </tr>
            <tr>
                <td> @Html.DisplayFor(modelItem => item.EventAct) </td>
            </tr>
            <tr>
                <td>
                    @Html.ActionLink("Detail","Index",new{id = item.ItemId})    |
                    Buy
                </td>
            </tr>
        </table>
        </td>
    </tr>
         </table>
    </td>
    if (count == 2)
    {<tr></tr>;
    }
}
</tr>
</table>
            </div>
    </section>
@section scripts{
    <script type="text/javascript">
        function getdataitem(id) {
            window.location("Item/Index/"+id);
        }
    </script>
}