musicstore/musicstore/Controllers/CreditController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace musicstore.Controllers
{
    public class CreditController : Controller
    {
        private DbAnggaEntities db = new DbAnggaEntities();

        //
        // GET: /Credit/

        public ActionResult Index()
        {
            var credits = db.credits.Include(c => c.item).Include(c => c.Member);
            return View(credits.ToList());
        }

        public ActionResult IndexPartial(int id = 0)
        {
            var listcredit = db.credits.Where(a => a.MemberId == id).Include(c => c.item).Include(c => c.Member).ToList();
            if (listcredit.Count == 0)
            {
                ViewBag.nul = true;
                return PartialView("_IndexPartial", null);
            }
            ViewBag.nul = false;
            return PartialView("_IndexPartial", listcredit);
        }

        //
        // GET: /Credit/Details/5

        public ActionResult Details(int id = 0)
        {
            credit credit = db.credits.Find(id);
            if (credit == null)
            {
                return HttpNotFound();
            }
            return View(credit);
        }

        //
        // GET: /Credit/Create

        public ActionResult Create()
        {
            ViewBag.ItemId = new SelectList(db.items, "ItemId", "ItemName");
            ViewBag.MemberId = new SelectList(db.Members, "MemberId", "MemberName");
            return View();
        }

        //
        // POST: /Credit/Create

        [HttpPost]
        public ActionResult Create(credit credit)
        {
            if (ModelState.IsValid)
            {
                db.credits.Add(credit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ItemId = new SelectList(db.items, "ItemId", "ItemName", credit.ItemId);
            ViewBag.MemberId = new SelectList(db.Members, "MemberId", "MemberName", credit.MemberId);
            return View(credit);
        }

        //
        // GET: /Credit/Edit/5

        public ActionResult Edit(int id = 0)
        {
            credit credit = db.credits.Find(id);
            if (credit == null)
            {
                return HttpNotFound();
            }
            ViewBag.ItemId = new SelectList(db.items, "ItemId", "ItemName", credit.ItemId);
            ViewBag.MemberId = new SelectList(db.Members, "MemberId", "MemberName", credit.MemberId);
            return View(credit);
        }

        //
        // POST: /Credit/Edit/5

        [HttpPost]
        public ActionResult Edit(credit credit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(credit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ItemId = new SelectList(db.items, "ItemId", "ItemName", credit.ItemId);
            ViewBag.MemberId = new SelectList(db.Members, "MemberId", "MemberName", credit.MemberId);
            return View(credit);
        }

        //
        // GET: /Credit/Delete/5

        public ActionResult Delete(int id = 0)
        {
            credit credit = db.credits.Find(id);
            if (credit == null)
            {
                return HttpNotFound();
            }
            return View(credit);
        }

        //
        // POST: /Credit/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            credit credit = db.credits.Find(id);
            db.credits.Remove(credit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

musicstore/musicstore/Controllers/TransMController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using musicstore.Models;

namespace musicstore.Controllers
{
    public class TransMController : Controller
    {
        private DbAnggaEntities db = new DbAnggaEntities();

        //
        // GET: /TransM/

        public ActionResult Index()
        {
            var trans_m = db.Trans_M.Include(t => t.Member);
            return View(trans_m.ToList());
        }

        public ViewResult indexjoin(int? page)
        {
            List<Trans_M> trans_m = new List<Trans_M>();
            foreach (var data in db.Trans_M)
            {
                Trans_M strans = new Trans_M();
                strans.TransId = data.TransId;
                strans.TransaDate = data.TransaDate;
                strans.MemberId = data.MemberId;
                strans.TotalTrans = data.TotalTrans;
                trans_m.Add(strans);
            }

            int pageSize = 1;
            int pageNumber = (page ?? 1);
            var tr = from t in trans_m
                     join m in db.Members.ToList()
                     on t.MemberId equals m.MemberId
                     select new
                     {
                         t.TransId,
                         t.TransaDate,
                         m.MemberName,
                         t.TotalTrans,
                     };
            var listtrans = tr.ToPagedList(pageNumber, pageSize);
            return View(listtrans);
        }

        public ViewResult indexx(int? page)
        {
            List<Trans_M> trans_m = new List<Trans_M>();
            foreach (var data in db.Trans_M)
            {
                Trans_M strans = new Trans_M();
                strans.TransId = data.TransId;
                strans.TransaDate = data.TransaDate;
                strans.MemberId = data.MemberId;
                strans.TotalTrans = data.TotalTrans;
                trans_m.Add(strans);
            }  
            
            int pageSize = 1;
            int pageNumber = (page ?? 1);
            var listtrans = trans_m.ToPagedList(pageNumber, pageSize);
            return View(listtrans);
        }

        private ViewResult View(IPagedList<Trans_M> listtrans, object listjoin)
        {
            throw new NotImplementedException();
        }

        //
        // GET: /TransM/Details/5

        public ActionResult Details(string id = null)
        {
            Trans_M trans_m = db.Trans_M.Find(id);
            if (trans_m == null)
            {
                return HttpNotFound();
            }
            return View(trans_m);
        }

        //
        // GET: /TransM/Create

        public ActionResult Create()
        {
            ViewBag.MemberId = new SelectList(db.Members, "MemberId", "MemberName");
            return View();
        }

        //
        // POST: /TransM/Create

        [HttpPost]
        public ActionResult Create(Trans_M trans_m)
        {
            if (ModelState.IsValid)
            {
                db.Trans_M.Add(trans_m);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MemberId = new SelectList(db.Members, "MemberId", "MemberName", trans_m.MemberId);
            return View(trans_m);
        }

        //
        // GET: /TransM/Edit/5

        public ActionResult Edit(string id = null)
        {
            Trans_M trans_m = db.Trans_M.Find(id);
            if (trans_m == null)
            {
                return HttpNotFound();
            }
            ViewBag.MemberId = new SelectList(db.Members, "MemberId", "MemberName", trans_m.MemberId);
            return View(trans_m);
        }

        //
        // POST: /TransM/Edit/5

        [HttpPost]
        public ActionResult Edit(Trans_M trans_m)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trans_m).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MemberId = new SelectList(db.Members, "MemberId", "MemberName", trans_m.MemberId);
            return View(trans_m);
        }

        //
        // GET: /TransM/Delete/5

        public ActionResult Delete(string id = null)
        {
            Trans_M trans_m = db.Trans_M.Find(id);
            if (trans_m == null)
            {
                return HttpNotFound();
            }
            return View(trans_m);
        }

        //
        // POST: /TransM/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string id)
        {
            Trans_M trans_m = db.Trans_M.Find(id);
            db.Trans_M.Remove(trans_m);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

musicstore/musicstore/Views/Credit/Create.cshtml
@model musicstore.credit

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>credit</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.MemberId, "Member")
        </div>
        <div class="editor-field">
            @Html.DropDownList("MemberId", String.Empty)
            @Html.ValidationMessageFor(model => model.MemberId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ItemId, "item")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ItemId", String.Empty)
            @Html.ValidationMessageFor(model => model.ItemId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.creditke)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.creditke)
            @Html.ValidationMessageFor(model => model.creditke)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.creditDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.creditDate)
            @Html.ValidationMessageFor(model => model.creditDate)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

musicstore/musicstore/Views/Credit/Delete.cshtml
@model musicstore.credit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>credit</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Member.MemberName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Member.MemberName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.item.ItemName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.item.ItemName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.creditke)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.creditke)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.creditDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.creditDate)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

musicstore/musicstore/Views/Credit/Details.cshtml
@model musicstore.credit

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>credit</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Member.MemberName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Member.MemberName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.item.ItemName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.item.ItemName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.creditke)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.creditke)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.creditDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.creditDate)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.creditId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

musicstore/musicstore/Views/Credit/Edit.cshtml
@model musicstore.credit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>credit</legend>

        @Html.HiddenFor(model => model.creditId)

        <div class="editor-label">
            @Html.LabelFor(model => model.MemberId, "Member")
        </div>
        <div class="editor-field">
            @Html.DropDownList("MemberId", String.Empty)
            @Html.ValidationMessageFor(model => model.MemberId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ItemId, "item")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ItemId", String.Empty)
            @Html.ValidationMessageFor(model => model.ItemId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.creditke)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.creditke)
            @Html.ValidationMessageFor(model => model.creditke)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.creditDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.creditDate)
            @Html.ValidationMessageFor(model => model.creditDate)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

musicstore/musicstore/Views/Credit/Index.cshtml
@model IEnumerable<musicstore.credit>

@{
    ViewBag.Title = "Index";
}

<header>
    <div class="content-wrapper">
        <div class="float-left">
            <p class="site-title">
                <img width="70PX" height="70PX" src="../Images/logo.png" />
                MVC Music Store
                </p>
        </div>
        
    </div>
    <br />
    <div class="content-wrapper">
        <nav>
            <ul id="menu">
                <li>@Html.ActionLink("Home","Index","Home")</li>
                <li>@Html.ActionLink("Member","Index","Member")</li>
                <li>@Html.ActionLink("Item","Index","Item")</li>
                <li>@Html.ActionLink("Category","Index","Category")</li>
                @*<li>@Html.ActionLink("Credit","Index","Credit")</li>*@
                <li>@Html.ActionLink("Transaction","indexx","TransM")</li>
            </ul>
        </nav>
    </div>
</header>

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Member.MemberName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.item.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.creditke)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.creditDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Member.MemberName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.item.ItemName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.creditke)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.creditDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.creditId }) |
            @Html.ActionLink("Details", "Details", new { id=item.creditId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.creditId })
        </td>
    </tr>
}

</table>

musicstore/musicstore/Views/Credit/_IndexPartial.cshtml
@model IEnumerable<musicstore.credit>

@{
    if(ViewBag.nul)
  {
   <h3>There is no Credit Data in This Member</h3>   
  }
  else{
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.item.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.item.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.creditke)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.creditDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>

        <td>
            @Html.DisplayFor(modelItem => item.item.ItemName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.creditke)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.creditDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.creditId }) |
            @*@Html.ActionLink("Details", "Details", new { id=item.creditId }) |*@
            @Html.ActionLink("Delete", "Delete", new { id=item.creditId })
        </td>
    </tr>
}

</table>
}
}